server:
  port: 80

spring:
   application:
    name: microservicecloud-consumer-dept-feign

eureka:
  client:
    register-with-eureka: true  #默认注册到eureka
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
        instance-id: microservicecloud-consumer-dept-feign    #自定义服务名称信息
        prefer-ip-address: true     #访问路径可以显示IP地址eureka

feign:
  hystrix:
    enabled: true  #开启客户端的hystrix服务降级

info:
  app.name: wchuang-microservicecloud
  company.name: www.wchuang.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$