server:
  port: 9527

spring:
  application:
    name: microservicecloud-zuul-gateway

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    instance-id: gateway-9527.com
    prefer-ip-address: true

zuul:
  prefix: /wchuang
  ignored-services: "*"
  routes:
    mydept.serviceId: microservicecloud-dept
    mydept.path: /mydept/**
    mydept-consumer.serviceId: microservicecloud-consumer-dept-feign
    mydept-consumer.path: /mydept-consumer/**

info:
  app.name: wchuang-microcloud
  company.name: www.wchuang.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$


